src/Entity/Bachillerato.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BachilleratoRepository")
 */
class Bachillerato
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $titulo;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $institucion;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_titulo;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\EmpleadoA", inversedBy="bachillerato")
     * @ORM\JoinColumn(nullable=false)
     */
    private $empleado_a;

    public function getId()
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getInstitucion(): ?string
    {
        return $this->institucion;
    }

    public function setInstitucion(string $institucion): self
    {
        $this->institucion = $institucion;

        return $this;
    }

    public function getFechaTitulo(): ?\DateTimeInterface
    {
        return $this->fecha_titulo;
    }

    public function setFechaTitulo(\DateTimeInterface $fecha_titulo): self
    {
        $this->fecha_titulo = $fecha_titulo;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEmpleadoA()
    {
        return $this->empleado_a;
    }

    /**
     * @param mixed $empleado_a
     */
    public function setEmpleadoA($empleado_a): void
    {
        $this->empleado_a = $empleado_a;
    }


}

src/Entity/Superior.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SuperiorRepository")
 */
class Superior
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $titulo;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $institucion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $registro_senescyt;

    /**
     * @ORM\Column(type="string", columnDefinition="ENUM('Tecnólogo', '3', '4')", length=255)
     * @Assert\Choice(choices = {"Tecnólogo","3", "4"})
     */
    private $nivel;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EmpleadoA", inversedBy="superiors")
     * @ORM\JoinColumn(nullable=false)
     */
    private $empleado_a;

    public function getId()
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getInstitucion(): ?string
    {
        return $this->institucion;
    }

    public function setInstitucion(string $institucion): self
    {
        $this->institucion = $institucion;

        return $this;
    }

    public function getRegistroSenescyt(): ?string
    {
        return $this->registro_senescyt;
    }

    public function setRegistroSenescyt(string $registro_senescyt): self
    {
        $this->registro_senescyt = $registro_senescyt;

        return $this;
    }

    public function getNivel(): ?string
    {
        return $this->nivel;
    }

    public function setNivel(string $nivel): self
    {
        $this->nivel = $nivel;

        return $this;
    }

    public function getEmpleadoA(): ?EmpleadoA
    {
        return $this->empleado_a;
    }

    public function setEmpleadoA(?EmpleadoA $empleado_a): self
    {
        $this->empleado_a = $empleado_a;

        return $this;
    }
}

src/Controller/EmpleadoAController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Bachillerato;
use App\Entity\EmpleadoA;
use App\Entity\Postbachillerato;
use App\Entity\Superior;
use App\Form\BachilleratoType;
use App\Form\EmpleadoAType;
use App\Form\PostbachilleratoType;
use App\Form\SuperiorType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class EmpleadoAController extends Controller
{

    private $encoder;

    public function __construct(UserPasswordEncoderInterface $encoder)
    {
       $this->encoder = $encoder;
    }
    /**
     * @Route("/empleado/a", name="empleado_a")
     */
    public function index()
    {
        return $this->render('empleado_a/index.html.twig', [
            'controller_name' => 'EmpleadoAController',
        ]);
    }

    /**
     * FUNCIÓN PARA CREAR UN NUEVO EMPLEADO A
     * @Route("/empleado/a/nuevo", name="empleadoA_nuevo")
     */
    public function crearEmpleadoA(Request $request){
        $empleado_a = new EmpleadoA();
        $form = $this->createForm(EmpleadoAType::class, $empleado_a);

        $form->handleRequest($request);
        $img = null;

        if ($form->isSubmitted() && $form->isValid()) {
            $empleado_a = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($empleado_a);
            $em->flush();
            $id= $empleado_a->getId();

            $nombre=  $empleado_a->getNombres(); 
            $apellido =  $empleado_a->getApellidos(); 
            $username = $nombre . " ". $apellido . " / C.I. ".$empleado_a->getCedula();

            /*Guardo credenciales de acceso del empleado en la table User */
            $manager = $this->getDoctrine()->getManager();
            $user = new User();
            $user->setUsername(
                $empleado_a->getCedula()
            );
            $user->setPassword(
                 $this->encoder->encodePassword($user, $empleado_a->getCedula())
            );
            $user->setEmail(
                 $username
            );
            $user->setRole(
                $empleado_a->getRol()
            );
            $manager->persist($user);
            $manager->flush();

            return $this->redirectToRoute('empleadoA_educacion', array(
                'id'=>$id
            ));
        }
        

        return $this->render('empleado_a/empleado_aCrear.html.twig', array(
            'formEmpleado_a' => $form->createView(), 'img'=>$img
        ));

    }

    /**
     * FUNCIÓN PARA EDITAR UN EMPLEADO A
     * @Route("/empleado/a/{id}/editar", name="empleadoA_editar")
     */
    public function editarEmpleadoA(Request $request, $id){
        $empleado_a = $this->getDoctrine()->getRepository(EmpleadoA::class)->find($id);
        $form = $this->createForm(EmpleadoAType::class, $empleado_a);

        $form->handleRequest($request);
        $img =$empleado_a->getFoto();

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            return $this->redirectToRoute('empleadoA_educacion', array(
                'id'=>$id
            ));
        }

        return $this->render('empleado_a/empleado_aCrear.html.twig', array(
            'formEmpleado_a' => $form->createView(),'img'=>$img
        ));

    }

    /**
     * FUNCIÓN PARA ELIMINAR UN EMPLEADO A
     * @Route("/empleado/a/{id}/eliminar", name="eliminar_empleadoA")
     */
    public function eliminarEmpleadoA($id){
        $em = $this->getDoctrine()->getManager();
        $bachillerato = $em->getRepository(Bachillerato::class)->findBy(
            ['empleado_a' => $id]
        );

        $postbachillerato = $this->getDoctrine()->getRepository(Postbachillerato::class)->findBy(
            ['empleado_a' => $id]
        );

        $superior = $this->getDoctrine()->getRepository(Superior::class)->findBy(
            ['empleado_a' => $id]
        );

        $empleado_a= $em->getRepository(EmpleadoA::class)->find($id);

        if (!$empleado_a) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        }
        foreach ($bachillerato as $bach) {
            $em->remove($bach);
        }
        foreach ($postbachillerato as $postbach) {
            $em->remove($postbach);
        }
        foreach ($superior as $super) {
            $em->remove($super);
        }

        $em->remove($empleado_a);
        $em->flush();

        return $this->redirectToRoute('empleados');

    }

    /**
     * VISTA PARA ELIMINAR UN EMPLEADO A
     * @Route("/empleado/a/{id}/vista/eliminar", name="vista_elminar_empleadoA")
     */
    public function vistaEliminarEmpleadoA($id){

        return $this->render('empleado_a/empleado_Aeliminar.html.twig', array(
            'id'=>$id,
        ));

    }



    /**
     * Returns a JSON string with the neighborhoods of the City with the providen id.
     * @Route("/get-neighborhoods-from-city", name="person_list_neighborhoods")
     * @Method("GET")
     * @param Request $request
     * @return JsonResponse
     */
    public function listNeighborhoodsOfCityAction(Request $request)
    {
        // Get Entity manager and repository
        $em = $this->getDoctrine()->getManager();
        $neighborhoodsRepository = $em->getRepository("App\Entity\Parroquia");

        // Search the neighborhoods that belongs to the city with the given id as GET parameter "cityid"
        $neighborhoods = $neighborhoodsRepository->createQueryBuilder("q")
            ->where("q.canton = :cityid")
            ->setParameter("cityid", $request->query->get("cityid"))
            ->getQuery()
            ->getResult();

        // Serialize into an array the data that we need, in this case only name and id
        // Note: you can use a serializer as well, for explanation purposes, we'll do it manually
        $responseArray = array();
        foreach($neighborhoods as $neighborhood){
            $responseArray[] = array(
                "id" => $neighborhood->getId(),
                "nombre" => $neighborhood->getNombre()
            );
        }

        // Return array with structure of the neighborhoods of the providen city id
        return new JsonResponse($responseArray);

        // e.g
        // [{"id":"3","name":"Treasure Island"},{"id":"4","name":"Presidio of San Francisco"}]
    }


    /**
     * FUNCIÓN PARA OBTENER EL VALOR DEL SUELDO SEGUN LA CATEGORÍA SELECCIONADA
     * @Route("/consulta_sueldo", name="consulta_sueldo")
     * @Method("GET")
     * @param Request $request
     * @return JsonResponse
     */
    public function consultaSueldo(Request $request)
    {
        // Obtener la Entity and repository
        $em = $this->getDoctrine()->getManager();
        $sueldo = $em->getRepository("App\Entity\Sueldo");

        // Consulta para buscar el valor del sueldo según la categoría
        $valor= $sueldo->createQueryBuilder("q")
            ->where("q.id = :sueldoid")
            ->setParameter("sueldoid", $request->query->get("sueldoid"))
            ->getQuery()
            ->getResult();

        // Poner en un array los datos o atributos que necesitamos, en este caso el id y el valor
        $responseArray = array();
        foreach($valor as $val){
            $responseArray[] = array(
                "id" => $val->getId(),
                "valor" => $val->getValor()
            );
        }

        // Retorna en un array los valores necesitados
        return new JsonResponse($responseArray);

        // ej.
        // [{"id":"3","valor":"1234"},{"id":"4","valor":"9876"}]
    }


    /**
     * FUNCIÓN PARA CREAR UN NUEVO BACHILLERATO
     * @Route("/empleado/a/nuevo/bachillerato/{id}", name="empleadoA_nuevoBachillerato")
     */
    public function crearEmpleadoABachillerato(Request $request, $id){

        //Verifico si hay datos en la tabla Bachillerato con el id del Empleado
        $bachilleratoData = $this->getDoctrine()
            ->getRepository(Bachillerato::class)
            ->findOneBy(['empleado_a'=>$id]);

        //Inicializo una varibale en caso de que exista o no datos con el id del Empleado en la tabla Bachillerato
        if (empty($bachilleratoData) == 0){
            $data = true;
        }else{
            $data = false;
        }

        $bachillerato = new Bachillerato();
        $form = $this->createForm(BachilleratoType::class, $bachillerato);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $bachillerato = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($bachillerato);
            $em->flush();

            return $this->redirectToRoute('empleadoA_educacion', array('id'=>$id));
        }

        return $this->render('empleado_a/bachillerato.html.twig', array(
            'formEmpleado_a' => $form->createView(),
            'id'=>$id,
            'data'=>$data
        ));
    }


    /**
     * FUNCIÓN PARA EDITAR UN BACHILLERATO
     * @Route("/empleado/a/nuevo/bachillerato/{id}/editar/{idEmpleado}", name="empleadoA_editarBachillerato")
     */
    public function editarEmpleadoABachillerato(Request $request, $id, $idEmpleado){

        $bachillerato = $this->getDoctrine()->getRepository(Bachillerato::class)->find($id);
        $form = $this->createForm(BachilleratoType::class, $bachillerato);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $bachillerato = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($bachillerato);
            $em->flush();

templates/empleado_a/bachillerato.html.twig
    {# SE ACTIVA EL BOTON DE AGREGAR PORQUE AUN NO EXISTE NINGUN REGISTRO#}
    {% if data == false %}
        <div class="text-right" style="padding: 8px">
            <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModalCenter1" >
                <i class="fas fa-plus"></i> Agregar
            </button>
        </div>
    {% endif %}

    {# SE DESACTIVA EL BOTON DE AGREGAR PORQUE YA EXISTE REGISTRO#}
    {% if data == true %}
        <div class="text-right" style="padding: 8px">
            <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModalCenter1" disabled>
                <i class="fas fa-plus"></i> Agregar
            </button>
        </div>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Registrar Bachillerato</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                {{ form_start(formEmpleado_a, {'action': path('empleadoA_nuevoBachillerato', {'id': id})}) }}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="titulo"><strong style="color: red">*</strong>Título Obtenido:</label>
                        {{ form_widget(formEmpleado_a.titulo, {'attr':{'class':'form-control form-control-sm'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="institucion"><strong style="color: red">*</strong>Institución:</label>
                        {{ form_widget(formEmpleado_a.institucion, {'attr':{'class':'form-control form-control-sm'}}) }}
                    </div>
                    <div class="form-group">
                        <label for="fecha_titulo"><strong style="color: red">*</strong>Fecha Título:</label>
                        {{ form_widget(formEmpleado_a.fecha_titulo, {'attr':{'class':'form-control form-control-sm'}}) }}
                    </div>
                    <div class="form-group" style="display: none">
                        <label for="empleado_a">Id EmpleadoA</label>
                        {{ form_widget(formEmpleado_a.empleado_a, {'attr':{'class':'form-control form-control-sm'}}) }}
                    </div>

                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

                    {{ form_widget(formEmpleado_a.guardar, {'attr':{'class':'btn btn-primary'}}) }}
                </div>

                {{ form_end(formEmpleado_a) }}

            </div>
        </div>
    </div>

    <p id="idEmpleadoA" style="display: none">{{ id }}</p>

{% block javascripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
        //OBTENGO EL ID DEL EMPLEADOA CREADO
        var idEmpleado = document.getElementById("idEmpleadoA").innerText;

        //SETTEO EL ID CON EL QUE SE VA AGUARDAR EL NUEVO BACHILLERATO
        $("#bachillerato_empleado_a").val(idEmpleado);

    </script>
{% endblock %}

templates/empleado_a/bachillerato_editar.html.twig
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModalCenter{{ id }}" >
        <i class="fas fa-edit"></i>
    </button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Editar Bachillerato</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            {{ form_start(formEmpleado_a, {'action': path('empleadoA_editarBachillerato', {'id': id, 'idEmpleado': idEmpleado})}) }}
            <div class="modal-body">
                <div class="form-group">
                    <label for="titulo"><strong style="color: red">*</strong>Título Obtenido:</label>
                    {{ form_widget(formEmpleado_a.titulo, {'attr':{'class':'form-control form-control-sm'}}) }}
                </div>
                <div class="form-group">
                    <label for="institucion"><strong style="color: red">*</strong>Institución:</label>
                    {{ form_widget(formEmpleado_a.institucion, {'attr':{'class':'form-control form-control-sm'}}) }}
                </div>
                <div class="form-group">
                    <label for="fecha_titulo"><strong style="color: red">*</strong>Fecha Título:</label>
                    {{ form_widget(formEmpleado_a.fecha_titulo, {'attr':{'class':'form-control form-control-sm'}}) }}
                </div>
                <div class="form-group" style="display: none">
                    <label for="empleado_a">Id EmpleadoA</label>
                    {{ form_widget(formEmpleado_a.empleado_a, {'attr':{'class':'form-control form-control-sm'}}) }}
                </div>

            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>

                {{ form_widget(formEmpleado_a.guardar, {'attr':{'class':'btn btn-primary'}}) }}
            </div>

            {{ form_end(formEmpleado_a) }}

        </div>
    </div>
</div>

templates/empleado_a/bachillerato_eliminar.html.twig
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal{{ id }}">
    <i class="fas fa-trash-alt"></i>
</button>

<div class="modal fade" id="exampleModal{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmacion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Esta seguro que desea eliminar el elemento?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">No</button>
                <a role="button" href="{{ path('empleadoA_eliminarBachillerato',{'id': id, 'idEmpleado': idEmpleado}) }}" class="btn btn-danger btn-sm">
                    Confirmar
                </a>
            </div>
        </div>
    </div>
</div>

templates/empleado_a/educacion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Educación{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css" rel="stylesheet" />
    <link href="{{ asset('css/empleado_a.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <fieldset style="padding-top: 0px">
        <legend>NIVEL DE INSTRUCCIÓN</legend>
        <div class="row">

            <div class="col-md-12">

                {{ render(controller(
                    'App\\Controller\\EmpleadoAController::crearEmpleadoABachillerato', {'id':idEmpladoA}
                )) }}

                <table id="tableBachillerato" class="hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Título Bachillerato</th>
                        <th>Institución</th>
                        <th>Fecha Título</th>
                        <th>Acción</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bach in bachillerato %}
                        <tr>
                            <td>{{ bach.titulo }}</td>
                            <td>{{ bach.institucion }}</td>
                            <td>{{ bach.fechaTitulo|date('Y-m-d') }}</td>
                            <td>
                                {{ render(controller(
                                    'App\\Controller\\EmpleadoAController::editarEmpleadoABachillerato', { 'id' : bach.id, 'idEmpleado': idEmpladoA}
                                )) }}
                                {{ render(controller(
                                    'App\\Controller\\EmpleadoAController::vistaEliminarBchillerato', { 'id' : bach.id,  'idEmpleado': idEmpladoA}
                                )) }}
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>

        <br>
        <hr>
        <br>

        <div class="row">

            <div class="col-md-12">

                {{ render(controller(
                    'App\\Controller\\EmpleadoAController::crearEmpleadoAPostbachillerato', {'id':idEmpladoA}
                )) }}

                <table id="tablePostbachillerato" class="hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Título Postbachillerato</th>
                        <th>Institución</th>
                        <th>Fecha Título</th>
                        <th>Acción</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bach in postbachillerato %}
                        <tr>
                            <td>{{ bach.titulo }}</td>
                            <td>{{ bach.institucion }}</td>
                            <td>{{ bach.fechaTitulo|date('Y-m-d') }}</td>
                            <td>
                                {{ render(controller(
                                    'App\\Controller\\EmpleadoAController::editarEmpleadoAPostbachillerato', { 'id' : bach.id, 'idEmpleado': idEmpladoA}
                                )) }}
                                {{ render(controller(
                                    'App\\Controller\\EmpleadoAController::vistaEliminarPostbachillerato', { 'id' : bach.id,  'idEmpleado': idEmpladoA}
                                )) }}
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>

        <br>
        <hr>
        <br>

        <div class="row">

            <div class="col-md-12">

                {{ render(controller(
                    'App\\Controller\\EmpleadoAController::crearEmpleadoASuperior', {'id':idEmpladoA}
                )) }}

                <table id="tableSuperior" class="hover" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Título Eduacación Superior</th>
                        <th>Institución</th>
                        <th>Reg. Senescyt</th>
                        <th>Nivel</th>
                        <th>Acción</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bach in superior %}
                        <tr>
                            <td>{{ bach.titulo }}</td>
                            <td>{{ bach.institucion }}</td>
                            <td>{{ bach.registroSenescyt }}</td>
                            <td>{{ bach.nivel }}</td>
                            <td>
                                {{ render(controller(
                                    'App\\Controller\\EmpleadoAController::editarEmpleadoASuperior', { 'id' : bach.id, 'idEmpleado': idEmpladoA}
                                )) }}
                                {{ render(controller(
                                    'App\\Controller\\EmpleadoAController::vistaEliminarSuperior', { 'id' : bach.id,  'idEmpleado': idEmpladoA}
                                )) }}
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>

        <br>

        <div class="row">
            <div class="col text-md-center">
                <a href="{{ path('empleadoA_editar', {'id': idEmpladoA}) }}" class="btn btn-primary">
                    Regresar
                </a>
                <a href="{{ path('empleados')}}" class="btn btn-primary">
                    Finalizar
                </a>
            </div>
        </div>
    </fieldset>

{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function() {
            $('#tableBachillerato').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
                },
                "searching": false,
                "paging": false,
                "info": false
            });
        } );

        $(document).ready(function() {
            $('#tablePostbachillerato').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
                },
                "searching": false,
                "paging": false,
                "info": false
            });
        } );

        $(document).ready(function() {
            $('#tableSuperior').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
                },
                "searching": false,
                "paging": false,
                "info": false
            });
        } );

    </script>
{% endblock %}

templates/empleado_a/empleado_Aeliminar.html.twig
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModalA{{ id }}">
    <i class="fas fa-trash-alt"></i>
</button>

<div class="modal fade" id="exampleModalA{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmacion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Esta seguro que desea eliminar el elemento?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">No</button>
                <a role="button" href="{{ path('eliminar_empleadoA',{'id': id}) }}" class="btn btn-danger btn-sm">
                    Confirmar
                </a>
            </div>
        </div>
    </div>
</div>

templates/empleado_a/postbachillerato_eliminar.html.twig
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModaldelete{{ id }}">
    <i class="fas fa-trash-alt"></i>
</button>

<div class="modal fade" id="exampleModaldelete{{ id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmacion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ¿Esta seguro que desea eliminar el elemento?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">No</button>
                <a role="button" href="{{ path('empleadoA_eliminarPostbachillerato',{'id': id, 'idEmpleado': idEmpleado}) }}" class="btn btn-danger btn-sm">
                    Confirmar
                </a>
            </div>
        </div>
    </div>
</div>